---
abstract: 'DBI extension for table_info as objects'
author:
  - 'Mark Lawrence <nomad@null.net>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test2::Bundle::Extended: '0'
  Test2::Require::Module: '0'
configure_requires:
  ExtUtils::MakeMaker::CPANfile: '0.09'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBIx-Model
no_index:
  directory:
    - t
    - inc
requires:
  DBI: '0'
  Scalar::Util: '0'
  Types::Standard: '0'
resources:
  repository: ssh://git@github.com/mlawren/p5-DBIx-Model.git
version: v0.0.1
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
